#!/usr/bin/env python

import sys, os
home_dir = os.path.expanduser('~')
home_dir += '/workspace/tk_trade_proj'
print home_dir
sys.path.append(home_dir)

import unittest
from tk_data_classes import *

class tk_data_classes_test_class(unittest.TestCase):

    def setUp(self):
        return

    def test_create_new_account(self):
        new_account = Account()
        self.assertIsNone(new_account.account_num)
        self.assertIsNone(new_account.accountval)
        self.assertIsNone(new_account.fedcall)
        self.assertIsNone(new_account.housecall)
        self.assertIsNone(new_account.accruedinterest)
        self.assertIsNone(new_account.cash)
        self.assertIsNone(new_account.cashavail)
        self.assertIsNone(new_account.marginbalance)
        self.assertIsNone(new_account.mmf)
        self.assertIsNone(new_account.total)
        self.assertIsNone(new_account.uncleareddeposits)
        self.assertIsNone(new_account.unsettledfunds)
        self.assertIsNone(new_account.account_yield)
        self.assertIsNone(new_account.longoptions)
        self.assertIsNone(new_account.longstocks)
        self.assertIsNone(new_account.options)
        self.assertIsNone(new_account.shortoptions)
        self.assertIsNone(new_account.shortstocks)
        self.assertIsNone(new_account.stocks)
        self.assertIsNone(new_account.total)
        self.assertIsNone(new_account.totalsecurities)

    def test_create_new_quote(self):
        new_quote = Quote()
        self.assertIsNone(new_quote.adp_100)
        self.assertIsNone(new_quote.adp_200)
        self.assertIsNone(new_quote.adp_50)
        self.assertIsNone(new_quote.adv_21)
        self.assertIsNone(new_quote.adv_30)
        self.assertIsNone(new_quote.adv_90)
        self.assertIsNone(new_quote.ask)
        self.assertIsNone(new_quote.ask_time)
        self.assertIsNone(new_quote.asksz)
        self.assertIsNone(new_quote.basis)
        self.assertIsNone(new_quote.beta)
        self.assertIsNone(new_quote.bid)
        self.assertIsNone(new_quote.bid_time)
        self.assertIsNone(new_quote.bidsz)
        self.assertIsNone(new_quote.bidtick)
        self.assertIsNone(new_quote.chg)
        self.assertIsNone(new_quote.chg_sign)
        self.assertIsNone(new_quote.chg_t)
        self.assertIsNone(new_quote.cl)
        self.assertIsNone(new_quote.contract_size)
        self.assertIsNone(new_quote.cusip)
        self.assertIsNone(new_quote.date)
        self.assertIsNone(new_quote.datetime)
        self.assertIsNone(new_quote.days_to_expiration)
        self.assertIsNone(new_quote.div)
        self.assertIsNone(new_quote.divexdate)
        self.assertIsNone(new_quote.divfreq)
        self.assertIsNone(new_quote.divpaydt)
        self.assertIsNone(new_quote.dollar_value)
        self.assertIsNone(new_quote.eps)
        self.assertIsNone(new_quote.exch)
        self.assertIsNone(new_quote.exch_desc)
        self.assertIsNone(new_quote.hi)
        self.assertIsNone(new_quote.iad)
        self.assertIsNone(new_quote.idelta)
        self.assertIsNone(new_quote.igamma)
        self.assertIsNone(new_quote.imp_volatility)
        self.assertIsNone(new_quote.incr_vl)
        self.assertIsNone(new_quote.irho)
        self.assertIsNone(new_quote.issue_desc)
        self.assertIsNone(new_quote.itheta)
        self.assertIsNone(new_quote.ivega)
        self.assertIsNone(new_quote.last)
        self.assertIsNone(new_quote.lo)
        self.assertIsNone(new_quote.name)
        self.assertIsNone(new_quote.op_delivery)
        self.assertIsNone(new_quote.op_flag)
        self.assertIsNone(new_quote.op_style)
        self.assertIsNone(new_quote.op_subclass)
        self.assertIsNone(new_quote.openinterest)
        self.assertIsNone(new_quote.opn)
        self.assertIsNone(new_quote.opt_val)
        self.assertIsNone(new_quote.pchg)
        self.assertIsNone(new_quote.pchg_sign)
        self.assertIsNone(new_quote.pcls)
        self.assertIsNone(new_quote.pe)
        self.assertIsNone(new_quote.phi)
        self.assertIsNone(new_quote.plo)
        self.assertIsNone(new_quote.popn)
        self.assertIsNone(new_quote.pr_adp_100)
        self.assertIsNone(new_quote.pr_adp_200)
        self.assertIsNone(new_quote.pr_adp_50)
        self.assertIsNone(new_quote.pr_date)
        self.assertIsNone(new_quote.pr_openinterest)
        self.assertIsNone(new_quote.prbook)
        self.assertIsNone(new_quote.prchg)
        self.assertIsNone(new_quote.prem_mult)
        self.assertIsNone(new_quote.put_call)
        self.assertIsNone(new_quote.pvol)
        self.assertIsNone(new_quote.qcond)
        self.assertIsNone(new_quote.rootsymbol)
        self.assertIsNone(new_quote.secclass)
        self.assertIsNone(new_quote.sesn)
        self.assertIsNone(new_quote.sho)
        self.assertIsNone(new_quote.strikeprice)
        self.assertIsNone(new_quote.symbol)
        self.assertIsNone(new_quote.tcond)
        self.assertIsNone(new_quote.timestamp)
        self.assertIsNone(new_quote.tr_num)
        self.assertIsNone(new_quote.tradetick)
        self.assertIsNone(new_quote.trend)
        self.assertIsNone(new_quote.under_cusip)
        self.assertIsNone(new_quote.undersymbol)
        self.assertIsNone(new_quote.vl)
        self.assertIsNone(new_quote.volatility12)
        self.assertIsNone(new_quote.vwap)
        self.assertIsNone(new_quote.wk52hi)
        self.assertIsNone(new_quote.wk52hidate)
        self.assertIsNone(new_quote.wk52lo)
        self.assertIsNone(new_quote.wk52lodate)
        self.assertIsNone(new_quote.xdate)
        self.assertIsNone(new_quote.xday)
        self.assertIsNone(new_quote.xmonth)
        self.assertIsNone(new_quote.xyear)
        self.assertIsNone(new_quote.account_yield)

    def test_create_new_search_quote(self):
        new_search_quote = Search_quote()
        self.assertIsNone(new_search_quote.ask)
        self.assertIsNone(new_search_quote.ask_time)
        self.assertIsNone(new_search_quote.asksz)
        self.assertIsNone(new_search_quote.basis)
        self.assertIsNone(new_search_quote.bid)
        self.assertIsNone(new_search_quote.bid_time)
        self.assertIsNone(new_search_quote.bidsz)
        self.assertIsNone(new_search_quote.chg)
        self.assertIsNone(new_search_quote.chg_sign)
        self.assertIsNone(new_search_quote.chg_t)
        self.assertIsNone(new_search_quote.cl)
        self.assertIsNone(new_search_quote.contract_size)
        self.assertIsNone(new_search_quote.date)
        self.assertIsNone(new_search_quote.datetime)
        self.assertIsNone(new_search_quote.days_to_expiration)
        self.assertIsNone(new_search_quote.exch)
        self.assertIsNone(new_search_quote.exch_desc)
        self.assertIsNone(new_search_quote.hi)
        self.assertIsNone(new_search_quote.incr_vl)
        self.assertIsNone(new_search_quote.issue_desc)
        self.assertIsNone(new_search_quote.last)
        self.assertIsNone(new_search_quote.lo)
        self.assertIsNone(new_search_quote.op_delivery)
        self.assertIsNone(new_search_quote.op_flag)
        self.assertIsNone(new_search_quote.op_style)
        self.assertIsNone(new_search_quote.op_subclass)
        self.assertIsNone(new_search_quote.opn)
        self.assertIsNone(new_search_quote.pchg)
        self.assertIsNone(new_search_quote.pchg_sign)
        self.assertIsNone(new_search_quote.pcls)
        self.assertIsNone(new_search_quote.phi)
        self.assertIsNone(new_search_quote.plo)
        self.assertIsNone(new_search_quote.popn)
        self.assertIsNone(new_search_quote.pr_date)
        self.assertIsNone(new_search_quote.pr_openinterest)
        self.assertIsNone(new_search_quote.prchg)
        self.assertIsNone(new_search_quote.prem_mult)
        self.assertIsNone(new_search_quote.put_call)
        self.assertIsNone(new_search_quote.pvol)
        self.assertIsNone(new_search_quote.rootsymbol)
        self.assertIsNone(new_search_quote.secclass)
        self.assertIsNone(new_search_quote.sesn)
        self.assertIsNone(new_search_quote.strikeprice)
        self.assertIsNone(new_search_quote.symbol)
        self.assertIsNone(new_search_quote.tcond)
        self.assertIsNone(new_search_quote.timestamp)
        self.assertIsNone(new_search_quote.tr_num)
        self.assertIsNone(new_search_quote.tradetick)
        self.assertIsNone(new_search_quote.under_cusip)
        self.assertIsNone(new_search_quote.undersymbol)
        self.assertIsNone(new_search_quote.vl)
        self.assertIsNone(new_search_quote.vwap)
        self.assertIsNone(new_search_quote.wk52hi)
        self.assertIsNone(new_search_quote.wk52hidate)
        self.assertIsNone(new_search_quote.wk52lo)
        self.assertIsNone(new_search_quote.wk52lodate)
        self.assertIsNone(new_search_quote.xdate)
        self.assertIsNone(new_search_quote.xday)
        self.assertIsNone(new_search_quote.xmonth)
        self.assertIsNone(new_search_quote.xyear)
        self.assertIsNone(new_search_quote.imp_volatility)
        self.assertIsNone(new_search_quote.idelta)
        self.assertIsNone(new_search_quote.igamma)
        self.assertIsNone(new_search_quote.itheta)
        self.assertIsNone(new_search_quote.ivega)
        self.assertIsNone(new_search_quote.irho)
        self.assertIsNone(new_search_quote.openinterest)


if __name__ == '__main__':
    unittest.main()